services:
  mysql:
    image: mysql:8.0
    container_name: findit-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: findit1234
      MYSQL_DATABASE: findit
      MYSQL_USER: findit
      MYSQL_PASSWORD: findit1234
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data: